source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers', '0.9.3'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
